/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.teamproject;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ApprovedPage extends javax.swing.JFrame {

    DatabaseConnection database;
    ResultSet rs = null;
    /**
     * Creates new form ApprovedPage
     */
    public ApprovedPage() {
        initComponents();
        database = new DatabaseConnection();
        UpdateApprovedTable();
    }
     private void UpdateApprovedTable(){
        database.Connect("events.db");
        //Query for pending events
        String sql = "SELECT * FROM events WHERE approved=1";
        try{
            rs = database.RunSQLQuery(sql);
        
            while(rs.next()){
                
                String id = String.valueOf(rs.getInt("event_id"));
                String Event = rs.getString("event_name");
                
                
                //String array to store the data in the jtable
                
                String tbData [] = {id, Event};
                DefaultTableModel DenyModel = (DefaultTableModel)ApprovedTable.getModel();
                
                //add the string array data into the jtable
                DenyModel.addRow(tbData);
            }
        } catch (Exception e){
                
        }
        
        
       
    }
     
     public void selectEvent(){
         
          int row = ApprovedTable.getSelectedRow();//get selected row index
        
        DefaultTableModel model = (DefaultTableModel)ApprovedTable.getModel();
        
        String EventName = model.getValueAt(row, 1).toString();
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ApprovedTable = new javax.swing.JTable();
        toDenied2 = new javax.swing.JButton();
        toPending2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        AddEventButton = new javax.swing.JButton();
        openAnalytics = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ApprovedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event ID", "Approved Event"
            }
        ));
        ApprovedTable.setPreferredSize(new java.awt.Dimension(700, 300));
        jScrollPane1.setViewportView(ApprovedTable);

        toDenied2.setText("Denied");
        toDenied2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toDenied2MouseClicked(evt);
            }
        });

        toPending2.setText("Pending");
        toPending2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toPending2MouseClicked(evt);
            }
        });

        jButton1.setText("LogOut");

        AddEventButton.setText("Add New Event");
        AddEventButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddEventButtonMouseClicked(evt);
            }
        });

        openAnalytics.setText("Open Analytics");
        openAnalytics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openAnalyticsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 94, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(400, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(openAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(toDenied2)
                                .addGap(18, 18, 18)
                                .addComponent(toPending2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(AddEventButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddEventButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(toPending2)
                    .addComponent(toDenied2)
                    .addComponent(openAnalytics))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toDenied2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toDenied2MouseClicked
        // TODO add your handling code here:
        
        this.dispose();
        DeniedPage obj = new DeniedPage();
        obj.setVisible(true);
        
    }//GEN-LAST:event_toDenied2MouseClicked

    private void toPending2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toPending2MouseClicked
        // TODO add your handling code here:
        
        this.dispose();
        ApprovedPage obj = new ApprovedPage();
        obj.setVisible(true);
    }//GEN-LAST:event_toPending2MouseClicked

    private void AddEventButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEventButtonMouseClicked
        // TODO add your handling code here:
        
        this.dispose();
        AddEventPage obj = new AddEventPage();
        obj.setVisible(true);
    }//GEN-LAST:event_AddEventButtonMouseClicked

    private void openAnalyticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openAnalyticsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        AnalyticsScreen obj = new AnalyticsScreen();
        obj.setVisible(true);
    }//GEN-LAST:event_openAnalyticsMouseClicked

    /**
     * @param args the commandtoPending2arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApprovedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApprovedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApprovedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApprovedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApprovedPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEventButton;
    private javax.swing.JTable ApprovedTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openAnalytics;
    private javax.swing.JButton toDenied2;
    private javax.swing.JButton toPending2;
    // End of variables declaration//GEN-END:variables
}
