/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.teamproject;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ApprovedPage extends javax.swing.JFrame {

    DatabaseConnection database;
    ResultSet rs = null;
    /**
     * Creates new form ApprovedPage
     */
    public ApprovedPage() {
        initComponents();
        database = new DatabaseConnection();
        UpdateApprovedTable();
    }
     private void UpdateApprovedTable(){
        database.Connect("events.db");
        //Query for pending events
        CompaniesQueries company = new CompaniesQueries(); // Create an instance of AnalyticsManager
        int companyID = company.selectCompany();
        String sql = "SELECT * FROM events WHERE approved=1 AND company_id="+companyID+";";
        try{
            rs = database.RunSQLQuery(sql);
        
            while(rs.next()){
                
                String id = String.valueOf(rs.getInt("event_id"));
                String Event = rs.getString("event_name");
                
                
                //String array to store the data in the jtable
                
                String tbData [] = {id, Event};
                DefaultTableModel DenyModel = (DefaultTableModel)ApprovedTable.getModel();
                
                //add the string array data into the jtable
                DenyModel.addRow(tbData);
            }
        } catch (Exception e){
                
        }
        
        
       
    }
     
     public void selectEvent(){
         
          int row = ApprovedTable.getSelectedRow();//get selected row index
        
        DefaultTableModel model = (DefaultTableModel)ApprovedTable.getModel();
        
        String EventName = model.getValueAt(row, 1).toString();
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ApprovedTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        AddEvents1 = new javax.swing.JButton();
        DeniedEvents1 = new javax.swing.JButton();
        AnalyticsEvents = new javax.swing.JButton();
        PendingEvents1 = new javax.swing.JButton();
        GoBack5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ApprovedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event ID", "Approved Event"
            }
        ));
        ApprovedTable.setPreferredSize(new java.awt.Dimension(700, 300));
        jScrollPane1.setViewportView(ApprovedTable);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AddEvents1.setText("Add Events");
        AddEvents1.setToolTipText("");
        AddEvents1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEvents1ActionPerformed(evt);
            }
        });

        DeniedEvents1.setText("Denied Events");
        DeniedEvents1.setToolTipText("");
        DeniedEvents1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeniedEvents1ActionPerformed(evt);
            }
        });

        AnalyticsEvents.setText("Analytics");
        AnalyticsEvents.setToolTipText("");
        AnalyticsEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticsEventsActionPerformed(evt);
            }
        });

        PendingEvents1.setText("Pending Events");
        PendingEvents1.setToolTipText("");
        PendingEvents1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingEvents1ActionPerformed(evt);
            }
        });

        GoBack5.setText("Log Out");
        GoBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBack5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GoBack5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddEvents1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeniedEvents1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AnalyticsEvents, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PendingEvents1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(AddEvents1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PendingEvents1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeniedEvents1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnalyticsEvents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoBack5)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEvents1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEvents1ActionPerformed

        this.dispose();
        AddEventPage obj = new AddEventPage();
        obj.setVisible(true);
    }//GEN-LAST:event_AddEvents1ActionPerformed

    private void DeniedEvents1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeniedEvents1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DeniedPage obj = new DeniedPage();
        obj.setVisible(true);
    }//GEN-LAST:event_DeniedEvents1ActionPerformed

    private void AnalyticsEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticsEventsActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AnalyticsScreen obj = new AnalyticsScreen();
        obj.setVisible(true);
    }//GEN-LAST:event_AnalyticsEventsActionPerformed

    private void PendingEvents1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingEvents1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PendingPage obj = new PendingPage();
        obj.setVisible(true);
    }//GEN-LAST:event_PendingEvents1ActionPerformed

    private void GoBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBack5ActionPerformed
        // TODO add your handling code here:
        UsersQueries manager = new UsersQueries();
        manager.logoutUser();
        this.dispose();
        LoginForm obj = new LoginForm();
        obj.setVisible(true);
    }//GEN-LAST:event_GoBack5ActionPerformed

    /**
     * @param args the commandtoPending2arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApprovedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApprovedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApprovedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApprovedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApprovedPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEvents1;
    private javax.swing.JButton AnalyticsEvents;
    private javax.swing.JTable ApprovedTable;
    private javax.swing.JButton DeniedEvents1;
    private javax.swing.JButton GoBack5;
    private javax.swing.JButton PendingEvents1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
