/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.teamproject;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class DeniedPage extends javax.swing.JFrame {

    DatabaseConnection database;
    ResultSet rs = null;
    /**
     * Creates new form DeniedPage
     */
    public DeniedPage() {
        initComponents();
        database = new DatabaseConnection();
        UpdateDeniedTable();
    }
    
        //updates the events shown in the tables for clients 
    private void UpdateDeniedTable(){
        database.Connect("events.db");
        //Query for pending events
        String sql = "SELECT * FROM denied_events";
        try{
            rs = database.RunSQLQuery(sql);
        
            while(rs.next()){
                
                String Event = rs.getString("event_name");
                String Reason = String.valueOf(rs.getInt("comment"));
                
                //String array to store the data in the jtable
                
                String tbData [] = {Event, Reason};
                DefaultTableModel DenyModel = (DefaultTableModel)PendingTable.getModel();
                
                //add the string array data into the jtable
                DenyModel.addRow(tbData);
            }
        } catch (Exception e){
                
        }
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PendingTable = new javax.swing.JTable();
        toApproved2 = new javax.swing.JButton();
        toPending = new javax.swing.JButton();
        GoBack4 = new javax.swing.JButton();
        AddEventButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 480));

        PendingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Denied", "Reason for Denial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(PendingTable);

        toApproved2.setText("Approved");
        toApproved2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toApproved2MouseClicked(evt);
            }
        });

        toPending.setText("Pending");
        toPending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toPendingMouseClicked(evt);
            }
        });

        GoBack4.setText("LogOut");

        AddEventButton.setText("Add New Event");
        AddEventButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddEventButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toApproved2)
                        .addGap(18, 18, 18)
                        .addComponent(toPending)
                        .addGap(18, 18, 18)
                        .addComponent(GoBack4))
                    .addComponent(AddEventButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddEventButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoBack4)
                    .addComponent(toApproved2)
                    .addComponent(toPending))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApproveButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApproveButton3ActionPerformed

    private void DenyButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenyButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DenyButton3ActionPerformed

    private void AddEventButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEventButtonMouseClicked
        // TODO add your handling code here:

        this.dispose();
        AddEventPage obj = new AddEventPage();
        obj.setVisible(true);
    }//GEN-LAST:event_AddEventButtonMouseClicked

    private void toPendingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toPendingMouseClicked
        // TODO add your handling code here:

        this.dispose();
        PendingPage obj = new PendingPage();
        obj.setVisible(true);
    }//GEN-LAST:event_toPendingMouseClicked

    private void toApproved2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toApproved2MouseClicked
        // TODO add your handling code here:

        this.dispose();
        ApprovedPage obj = new ApprovedPage();
        obj.setVisible(true);
    }//GEN-LAST:event_toApproved2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeniedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeniedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeniedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeniedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeniedPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEventButton;
    private javax.swing.JButton GoBack4;
    private javax.swing.JTable PendingTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton toApproved2;
    private javax.swing.JButton toPending;
    // End of variables declaration//GEN-END:variables
}
