/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.teamproject;
import java.sql.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author User
 */
public class PendingPage extends javax.swing.JFrame {

     DatabaseConnection database;
     ResultSet rs = null;
    /**
     * Creates new form PendingPage
     */
    public PendingPage() {
        initComponents();
        database = new DatabaseConnection();
        UpdatePendingTable();
    }
    
    //updates the events shown in the tables for clients 
    private void UpdatePendingTable(){
        database.Connect("events.db");
        //Query for pending events
        String sql = "SELECT * FROM events WHERE approved=0";
        try{
            rs = database.RunSQLQuery(sql);
        
            while(rs.next()){
                String id = String.valueOf(rs.getInt("event_id"));
                String Event = rs.getString("event_name");
                
                //String array to store the data in the jtable
                
                String tbData [] = {id, Event};
                DefaultTableModel PendModel = (DefaultTableModel)PendingTable.getModel();
                
                //add the string array data into the jtable
                PendModel.addRow(tbData);
            }
        } catch (Exception e){
                
        }
        
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PendingTable = new javax.swing.JTable();
        ViewButton1 = new javax.swing.JButton();
        GoBack1 = new javax.swing.JButton();
        DenyButton1 = new javax.swing.JButton();
        ApproveButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PendingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Event ID", "Pending"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(PendingTable);

        ViewButton1.setText("View");

        GoBack1.setText("Go Back");

        DenyButton1.setText("Denied");

        ApproveButton1.setText("Approved");
        ApproveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ApproveButton1)
                        .addGap(18, 18, 18)
                        .addComponent(DenyButton1)
                        .addGap(18, 18, 18)
                        .addComponent(ViewButton1)
                        .addGap(18, 18, 18)
                        .addComponent(GoBack1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewButton1)
                    .addComponent(GoBack1)
                    .addComponent(DenyButton1)
                    .addComponent(ApproveButton1))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApproveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApproveButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApproveButton1;
    private javax.swing.JButton DenyButton1;
    private javax.swing.JButton GoBack1;
    private javax.swing.JTable PendingTable;
    private javax.swing.JButton ViewButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
